version: "3.7"

services:
  web:
    image: nginx:1.17
    ports:
      - "8080:80"
    volumes:
      - ./code:/var/www
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./code:/var/www
